### ISSUE TITLE
Delete files from cache

### ISSUE THREAD

**Issue by ManuDeBuck** [dessibelle/sorl-thumbnail-serializer-field#13]
Is there a way to (automatically) remove all the created thumbnails in the cache folder? I did try the delete function from sorl itself but that didn't work.

I'm using this function

```python
@receiver(post_delete, sender=Image)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
```

to delete the original file when deleting my model, but the thumbnail-files in the cache will not be removed by doing this.

**Comment by dessibelle** [comment]
I guess that's outside the scope of sorl-thumbnail-serializer-field. As it just uses sorl-thumbnail to generate image and cache them, storage and persistence would probably be controlled using sor-thumbnail's cache settings, and possibly some Django cache backend settings.

It sounds a bit like this is sort of what you already tried out, but I'd assume [sorl-thumbnail management commands](https://sorl-thumbnail.readthedocs.io/en/latest/management.html) would remove cached images, and if not there's probably something wrong with the cache setup. 

With that said, I do very little Django development these days, and has not been using sorl-thumbnail-serializer-field in a few years myself, so things may very well have changed since this code was written 3-4 years ago.

**Comment by ManuDeBuck** [comment]
Thank you very much for your answer. I digged a little deeper into the `sorl-thumbnail` documentation and I did indeed find a settings parameter that would let me decide how long to store files in the cache.

**Comment by ManuDeBuck** [comment]
If anyone stumbles upon this issue in the future, this is how I could solve it (without using the setting parameters):

```python
@receiver(post_delete, sender=Image)
def submission_delete(sender, instance, **kwargs):
    sorl.thumbnail.delete(instance.image, delete_file=True)
```
