### ISSUE TITLE
Upgrade djangorestframework dependency

### ISSUE THREAD

**Issue by jwicks** [dessibelle/sorl-thumbnail-serializer-field#8]
Love this serializer. Do you mind upgrading the dependency on `djangorestframework==3.2.3` to something more recent/less strict? Eg. `djangorestframework>=3.2.0`

```
    install_requires=[
        'Django>=1.5.0',
        'djangorestframework==3.2.3',
        'sorl-thumbnail==12.3',
    ],
```

**Comment by GitRon** [comment]
👍

**Comment by dessibelle** [comment]
Hey @jwicks, glad to hear you're finding it useful! It was a while since I used sorl-thumbnail-serializer-field myself, which is why the development has sort of halted. 

That version requirement look really odd, if I remember correctly there was a PR a while back that added 3.0 support. Something like `>=` would definitely make more sense. I'll have a look at that as soon as I can.
